var word_list = [
        {text: "PHP", weight: 13, link: {href: "javascript:;"}},
        {text: "Yii Framework", weight: 10.5,link: {href: "javascript:;"}},
        {text: "HTML5", weight: 9.4, link: {href: "javascript:;"}},
        {text: "SaaS", weight: 9, link: {href: "javascript:;"}},
        {text: "CSS3", weight: 8, link: {href: "javascript:;"}},
        {text: "Symfony", weight: 7.5, link: {href: "javascript:;"}},
        {text: "Design Patterns", weight: 7, link: {href: "javascript:;"}},
        {text: "ExtJS", weight: 4.2, link: {href: "javascript:;"}},
        {text: "Cloud Computing", weight: 5, link: {href: "javascript:;"}},
        {text: "Scrum", weight: 5, link: {href: "javascript:;"}},
        {text: "GIT", weight: 5.5, link: {href: "javascript:;"}},
        {text: "Extreme Programming", weight: 5, link: {href: "javascript:;"}},
        {text: "Agile", weight: 5, link: {href: "javascript:;"}},
        {text: "AngularJS", weight: 7, link: {href: "javascript:;"}},
        {text: "JQuery", weight: 4, link: {href: "javascript:;"}},
        {text: "MySQL", weight: 4, link: {href: "javascript:;"}},
        {text: "Json", weight: 4, link: {href: "javascript:;"}},
        {text: "SEO", weight: 4, link: {href: "javascript:;"}},
        {text: "CodeIgniter", weight: 3, link: {href: "javascript:;"}},
        {text: "Usabilidade", weight: 3, link: {href: "javascript:;"}},
        {text: "Acessibilidade", weight: 3, link: {href: "javascript:;"}},
        {text: "Kanban", weight: 3, link: {href: "javascript:;"}},
        {text: "Responsive Layout", weight: 3, link: {href: "javascript:;"}},
        {text: "AJAX", weight: 3, link: {href: "javascript:;"}},
        {text: "Grid Layout", weight: 3, link: {href: "javascript:;"}},
        {text: "Google", weight: 3, link: {href: "javascript:;"}},
        {text: "Microsoft", weight: 2, link: {href: "javascript:;"}},
        {text: "LINUX", weight: 3, link: {href: "javascript:;"}},
        {text: "ANDROID", weight: 3, link: {href: "javascript:;"}},
        {text: "FrontEnd", weight: 2, link: {href: "javascript:;"}},
        {text: "BackEnd", weight: 2, link: {href: "javascript:;"}},
        {text: "RESTful", weight: 2, link: {href: "javascript:;"}},
        {text: "Frameworks", weight: 2, link: {href: "javascript:;"}},
        {text: "Mobile", weight: 2, link: {href: "javascript:;"}},
        {text: "ZEND", weight: 2, link: {href: "javascript:;"}},
        {text: "DEVELOPER", weight: 2, link: {href: "javascript:;"}},
        {text: "Tableless", weight: 2, link: {href: "javascript:;"}},
        {text: "RSS", weight: 1, link: {href: "javascript:;"}},
        {text: "W3C", weight: 1, link: {href: "javascript:;"}},
        {text: "XML", weight: 1, link: {href: "javascript:;"}},
        {text: "FourSquare", weight: 1, link: {href: "javascript:;"}},
        {text: "Instagram", weight: 1, link: {href: "javascript:;"}},
        {text: "Linkedin", weight: 1, link: {href: "javascript:;"}},
        {text: "GooglePlus", weight: 1, link: {href: "javascript:;"}},
        {text: "Facebook", weight: 3, link: {href: "javascript:;"}},
        {text: "Twitter", weight: 1, link: {href: "javascript:;"}},
        {text: "IOS", weight: 1, link: {href: "javascript:;"}},
        {text: "JAVA", weight: 1, link: {href: "javascript:;"}},
        {text: "JavaScript", weight: 1, link: {href: "javascript:;"}},
        {text: "HTML", weight: 1, link: {href: "javascript:;"}},
        {text: "CSS", weight: 1, link: {href: "javascript:;"}}
      ];
      $(function() {
        $("#tagcloud").jQCloud(word_list);
      });